### ISSUE TITLE
Potential issues in`timeout_payment_intent` 

### ISSUE THREAD

**Issue by vovayartsev** [errkk/ticketytock#4]
Hey Eric,

The solution with `timeout_payment_intent` seems to be a bit fragile: `spawn + :timer.sleep` it's not resilient to Heroku dyno restarts.

Let's analyze it: what bad things may happen if a dyno restarts?

**Comment by errkk** [comment]
Yeh, this isn't ideal. I wanted to show that I'd considered the fact that Stripe doesn't know about the expiry window for ticket purchasing that's maintained in the ticket table on the Phoenix app. 

A completed Stripe payment would in this case not be able to secure a ticket, so it would need to be refunded. So canceling the intent felt like it would at least stop the user from going through the effort of paying.

Of course if the dyno restarts, the timeout task will be lost and the request to cancel the intent will never be made.

Whilst I could go down a route of OTP's zero-downtime updates, I feel like waiting for actual time to elapse before doing something isn't ideal. Ideally the expiry date can be shared up front, and all parties know when the thing is no longer valid. I didn't manage to find something like this in the `create_intent` API.

Looking a bit more in the Stripe API...
Perhaps what would be better is to make the `PaymentIntent` with `capture_method=manual` and capture the payment right after this step is completed so that the window can be checked again.

**Comment by vovayartsev** [comment]
>  to make the PaymentIntent with `capture_method=manual` and capture the payment right after this step is completed so that the window can be checked again.

Accepted ✅
